
services:
  app: &app
    image: swark/swark:latest
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=swark
      - DB_PASSWORD=swark
      - DB_DATABASE=swark
      - ADMIN_EMAIL=me@domain.com
      # leave empty to generate a random password
      # - ADMIN_PASSWORD=myrandompassword
      # Enable database migrations
      - AUTORUN_ENABLED=true
      # switch to German locale
      # - APP_LOCALE=de
      - APP_KEY=Th1s1sARandom5tringW1thLength32.
      # where to find our static content? Use git to store that
      - SWARK_CONTENT_PATH=./swark_content
    ports:
      - "8080:8080" 
      - "8443:8443" 
    volumes:
      - laravel_data:/var/www/html/storage
      - swark_data:/var/www/html/swark_content
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_PASSWORD=swark
      - MARIADB_DATABASE=swark
      - MARIADB_USER=swark
    ports:
      - "33060:3306"
    volumes:
      - mariadbsqldata:/var/lib/mariadb
    restart: always

#  cron:
#    <<: *app
#    command: cron.sh

#  queue:
#    <<: *app
#    command: queue.sh

volumes:
  laravel_data:
    driver: local
  swark_data:
    driver: local
  mariadbsqldata:
    driver: local